<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Self-study preparation file">
<meta name="dcterms.date" content="2026-01-01">

<title>BAN404 R Exam Compendium</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ExamPrep_files/libs/clipboard/clipboard.min.js"></script>
<script src="ExamPrep_files/libs/quarto-html/quarto.js"></script>
<script src="ExamPrep_files/libs/quarto-html/popper.min.js"></script>
<script src="ExamPrep_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ExamPrep_files/libs/quarto-html/anchor.min.js"></script>
<link href="ExamPrep_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ExamPrep_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ExamPrep_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ExamPrep_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ExamPrep_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#task-1-regression-continuous-outcome" id="toc-task-1-regression-continuous-outcome" class="nav-link active" data-scroll-target="#task-1-regression-continuous-outcome"><span class="header-section-number">1</span> Task 1: Regression (Continuous Outcome)</a>
  <ul>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda"><span class="header-section-number">1.1</span> 1.1 Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#data-integrity-check" id="toc-data-integrity-check" class="nav-link" data-scroll-target="#data-integrity-check"><span class="header-section-number">1.1.1</span> Data Integrity Check</a></li>
  <li><a href="#distribution-of-the-target-variable-y" id="toc-distribution-of-the-target-variable-y" class="nav-link" data-scroll-target="#distribution-of-the-target-variable-y"><span class="header-section-number">1.1.2</span> Distribution of the Target Variable (y)</a></li>
  <li><a href="#multicollinearity-and-feature-scaling" id="toc-multicollinearity-and-feature-scaling" class="nav-link" data-scroll-target="#multicollinearity-and-feature-scaling"><span class="header-section-number">1.1.3</span> Multicollinearity and Feature Scaling</a></li>
  <li><a href="#checking-the-linearity-assumption" id="toc-checking-the-linearity-assumption" class="nav-link" data-scroll-target="#checking-the-linearity-assumption"><span class="header-section-number">1.1.4</span> Checking the Linearity Assumption</a></li>
  <li><a href="#eda-findings" id="toc-eda-findings" class="nav-link" data-scroll-target="#eda-findings"><span class="header-section-number">1.1.5</span> EDA Findings</a></li>
  </ul></li>
  <li><a href="#data-preparation-splitting" id="toc-data-preparation-splitting" class="nav-link" data-scroll-target="#data-preparation-splitting"><span class="header-section-number">1.2</span> 1.2 Data Preparation (Splitting)</a></li>
  <li><a href="#linear-parametric-models-baselines" id="toc-linear-parametric-models-baselines" class="nav-link" data-scroll-target="#linear-parametric-models-baselines"><span class="header-section-number">1.3</span> 1.3 Linear &amp; Parametric Models (Baselines)</a>
  <ul class="collapse">
  <li><a href="#ols-baseline" id="toc-ols-baseline" class="nav-link" data-scroll-target="#ols-baseline"><span class="header-section-number">1.3.1</span> OLS Baseline</a></li>
  <li><a href="#polynomial-regression-fixing-ols-manually" id="toc-polynomial-regression-fixing-ols-manually" class="nav-link" data-scroll-target="#polynomial-regression-fixing-ols-manually"><span class="header-section-number">1.3.2</span> Polynomial Regression (Fixing OLS Manually)</a></li>
  </ul></li>
  <li><a href="#regularization-variable-selection" id="toc-regularization-variable-selection" class="nav-link" data-scroll-target="#regularization-variable-selection"><span class="header-section-number">1.4</span> 1.4 Regularization &amp; Variable Selection</a>
  <ul class="collapse">
  <li><a href="#lasso-regression" id="toc-lasso-regression" class="nav-link" data-scroll-target="#lasso-regression"><span class="header-section-number">1.4.1</span> LASSO Regression</a></li>
  </ul></li>
  <li><a href="#flexible-non-parametric-models" id="toc-flexible-non-parametric-models" class="nav-link" data-scroll-target="#flexible-non-parametric-models"><span class="header-section-number">1.5</span> 1.5 Flexible &amp; Non-Parametric Models</a>
  <ul class="collapse">
  <li><a href="#generalized-additive-models-gam" id="toc-generalized-additive-models-gam" class="nav-link" data-scroll-target="#generalized-additive-models-gam"><span class="header-section-number">1.5.1</span> Generalized Additive Models (GAM)</a></li>
  <li><a href="#tree-based-ensemble-random-forest" id="toc-tree-based-ensemble-random-forest" class="nav-link" data-scroll-target="#tree-based-ensemble-random-forest"><span class="header-section-number">1.5.2</span> Tree-Based Ensemble (Random Forest)</a></li>
  <li><a href="#boosting-gradient-boosted-trees" id="toc-boosting-gradient-boosted-trees" class="nav-link" data-scroll-target="#boosting-gradient-boosted-trees"><span class="header-section-number">1.5.3</span> Boosting (Gradient Boosted Trees)</a></li>
  </ul></li>
  <li><a href="#final-evaluation-the-bias-variance-tradeoff" id="toc-final-evaluation-the-bias-variance-tradeoff" class="nav-link" data-scroll-target="#final-evaluation-the-bias-variance-tradeoff"><span class="header-section-number">1.6</span> 1.6 Final Evaluation: The Bias-Variance Tradeoff</a></li>
  <li><a href="#theoretical-curveballs-inference-resampling" id="toc-theoretical-curveballs-inference-resampling" class="nav-link" data-scroll-target="#theoretical-curveballs-inference-resampling"><span class="header-section-number">1.7</span> 1.7 Theoretical Curveballs (Inference &amp; Resampling)</a>
  <ul class="collapse">
  <li><a href="#the-bootstrap-normal-vs.-percentile-cis" id="toc-the-bootstrap-normal-vs.-percentile-cis" class="nav-link" data-scroll-target="#the-bootstrap-normal-vs.-percentile-cis"><span class="header-section-number">1.7.1</span> The Bootstrap (Normal vs.&nbsp;Percentile CIs)</a></li>
  <li><a href="#ridge-regression-vs.-lasso-comparing-penalties" id="toc-ridge-regression-vs.-lasso-comparing-penalties" class="nav-link" data-scroll-target="#ridge-regression-vs.-lasso-comparing-penalties"><span class="header-section-number">1.7.2</span> Ridge Regression vs.&nbsp;LASSO (Comparing Penalties)</a></li>
  <li><a href="#manual-k-fold-cross-validation-loop" id="toc-manual-k-fold-cross-validation-loop" class="nav-link" data-scroll-target="#manual-k-fold-cross-validation-loop"><span class="header-section-number">1.7.3</span> Manual K-Fold Cross-Validation Loop</a></li>
  <li><a href="#manual-k-fold-cross-validation-loop-best-practice" id="toc-manual-k-fold-cross-validation-loop-best-practice" class="nav-link" data-scroll-target="#manual-k-fold-cross-validation-loop-best-practice"><span class="header-section-number">1.7.4</span> Manual K-Fold Cross-Validation Loop (Best Practice)</a></li>
  <li><a href="#confidence-vs.-prediction-intervals" id="toc-confidence-vs.-prediction-intervals" class="nav-link" data-scroll-target="#confidence-vs.-prediction-intervals"><span class="header-section-number">1.7.5</span> Confidence vs.&nbsp;Prediction Intervals</a></li>
  </ul></li>
  <li><a href="#typical-exam-discussion-questions-theory-interpretation" id="toc-typical-exam-discussion-questions-theory-interpretation" class="nav-link" data-scroll-target="#typical-exam-discussion-questions-theory-interpretation"><span class="header-section-number">1.8</span> 1.8 Typical Exam Discussion Questions (Theory &amp; Interpretation)</a>
  <ul class="collapse">
  <li><a href="#q1-gam-vs.-manual-polynomial" id="toc-q1-gam-vs.-manual-polynomial" class="nav-link" data-scroll-target="#q1-gam-vs.-manual-polynomial"><span class="header-section-number">1.8.1</span> Q1: GAM vs.&nbsp;Manual Polynomial</a></li>
  <li><a href="#q2-lasso-vs.-ridge-regression" id="toc-q2-lasso-vs.-ridge-regression" class="nav-link" data-scroll-target="#q2-lasso-vs.-ridge-regression"><span class="header-section-number">1.8.2</span> Q2: LASSO vs.&nbsp;Ridge Regression</a></li>
  <li><a href="#q3-bias-variance-tradeoff-in-ensembles" id="toc-q3-bias-variance-tradeoff-in-ensembles" class="nav-link" data-scroll-target="#q3-bias-variance-tradeoff-in-ensembles"><span class="header-section-number">1.8.3</span> Q3: Bias-Variance Tradeoff in Ensembles</a></li>
  <li><a href="#q4-the-danger-of-interpreting-ols-p-values-blindly" id="toc-q4-the-danger-of-interpreting-ols-p-values-blindly" class="nav-link" data-scroll-target="#q4-the-danger-of-interpreting-ols-p-values-blindly"><span class="header-section-number">1.8.4</span> Q4: The Danger of Interpreting OLS p-values blindly</a></li>
  <li><a href="#q5-bootstrapping-vs.-asymptotic-theory" id="toc-q5-bootstrapping-vs.-asymptotic-theory" class="nav-link" data-scroll-target="#q5-bootstrapping-vs.-asymptotic-theory"><span class="header-section-number">1.8.5</span> Q5: Bootstrapping vs.&nbsp;Asymptotic Theory</a></li>
  <li><a href="#q6-interpretability-vs.-flexibility" id="toc-q6-interpretability-vs.-flexibility" class="nav-link" data-scroll-target="#q6-interpretability-vs.-flexibility"><span class="header-section-number">1.8.6</span> Q6: Interpretability vs.&nbsp;Flexibility</a></li>
  <li><a href="#q7-the-role-of-mtry-in-random-forests" id="toc-q7-the-role-of-mtry-in-random-forests" class="nav-link" data-scroll-target="#q7-the-role-of-mtry-in-random-forests"><span class="header-section-number">1.8.7</span> Q7: The Role of <code>mtry</code> in Random Forests</a></li>
  <li><a href="#q8-evaluating-out-of-sample-performance" id="toc-q8-evaluating-out-of-sample-performance" class="nav-link" data-scroll-target="#q8-evaluating-out-of-sample-performance"><span class="header-section-number">1.8.8</span> Q8: Evaluating Out-of-Sample Performance</a></li>
  <li><a href="#q9-overfitting-in-boosting" id="toc-q9-overfitting-in-boosting" class="nav-link" data-scroll-target="#q9-overfitting-in-boosting"><span class="header-section-number">1.8.9</span> Q9: Overfitting in Boosting</a></li>
  <li><a href="#q10-feature-importance-in-trees-vs.-linear-coefficients" id="toc-q10-feature-importance-in-trees-vs.-linear-coefficients" class="nav-link" data-scroll-target="#q10-feature-importance-in-trees-vs.-linear-coefficients"><span class="header-section-number">1.8.10</span> Q10: Feature Importance in Trees vs.&nbsp;Linear Coefficients</a></li>
  <li><a href="#q11-bias-reduction-vs.-variance-reduction-in-this-dataset" id="toc-q11-bias-reduction-vs.-variance-reduction-in-this-dataset" class="nav-link" data-scroll-target="#q11-bias-reduction-vs.-variance-reduction-in-this-dataset"><span class="header-section-number">1.8.11</span> Q11: Bias Reduction vs.&nbsp;Variance Reduction in this Dataset</a></li>
  <li><a href="#q12-justifying-specific-code-choices-the-gam-formula" id="toc-q12-justifying-specific-code-choices-the-gam-formula" class="nav-link" data-scroll-target="#q12-justifying-specific-code-choices-the-gam-formula"><span class="header-section-number">1.8.12</span> Q12: Justifying Specific Code Choices (The GAM Formula)</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ExamPrep.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BAN404 R Exam Compendium</h1>
<p class="subtitle lead">Comprehensive solution guide — 2023, 2024, and 2025 school exams</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Self-study preparation file </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>General Setup and Package Loading</strong></p>
<p>Before tackling any specific task, we load the standard suite of BAN404 packages. We use <code>tidyverse</code> for data manipulation and visualization, <code>janitor</code> for safe column naming, and the core statistical learning packages (<code>glmnet</code>, <code>gam</code>, <code>tree</code>, <code>randomForest</code>, <code>gbm</code>) so we don’t have to interrupt our workflow later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0. Load necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)       <span class="co"># Regularization (Ridge/LASSO)</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gam)          <span class="co"># Generalized Additive Models (Non-linearities)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tree)         <span class="co"># Decision Trees</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest) <span class="co"># Bagging and Random Forests</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gbm)          <span class="co"># Boosting</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Load the datasets safely</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># show_col_types = FALSE keeps the exam output clean. </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># clean_names() ensures no weird spaces or characters in column names.</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>df_task1 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"task1_data.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>df_customer <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"customer_data.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span> <span class="fu">clean_names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="task-1-regression-continuous-outcome" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Task 1: Regression (Continuous Outcome)</h1>
<p>Before fitting any models, we must understand the data generating process. The goal of this Exploratory Data Analysis (EDA) is to inform our model selection. We will systematically now do checks for:</p>
<ol type="1">
<li>Data integrity (Missing values)</li>
<li>Target distribution (Skewness / Outliers)</li>
<li>Feature independence (Multicollinearity)</li>
<li>Functional form (Linearity vs.&nbsp;Non-linearity)</li>
</ol>
<section id="exploratory-data-analysis-eda" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="exploratory-data-analysis-eda"><span class="header-section-number">1.1</span> 1.1 Exploratory Data Analysis (EDA)</h2>
<section id="data-integrity-check" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="data-integrity-check"><span class="header-section-number">1.1.1</span> Data Integrity Check</h3>
<p><strong>Reasoning:</strong> Many machine learning algorithms (like standard Random Forests or <code>lm()</code> without <code>na.action</code> adjustments) will fail or drop rows entirely if missing values are present. We must verify completeness first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values in each column</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(df_task1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>x1 x2 x3 x4 x5 x6  y 
 0  0  0  0  0  0  0 </code></pre>
</div>
</div>
<p><em>Conclusion:</em> There are 0 missing values. The dataset is complete, so no imputation is necessary.</p>
</section>
<section id="distribution-of-the-target-variable-y" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="distribution-of-the-target-variable-y"><span class="header-section-number">1.1.2</span> Distribution of the Target Variable (y)</h3>
<p><strong>Reasoning:</strong> The distribution of the continuous outcome <code>y</code> tells us if we need to transform the data. Severe skewness can violate OLS residual assumptions and make the model overly sensitive to outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_task1, <span class="fu">aes</span>(<span class="at">x =</span> y)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">50</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Target Variable (y)"</span>, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Checking for severe skewness or extreme outliers"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_target_dist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Conclusion:</em> The histogram shows a right-skewed distribution with a long tail extending towards 50. Normally, this suggests a <code>log(y)</code> transformation. However, <strong>the data contains negative values (down to approximately -8)</strong>. Because <span class="math inline">\(\log(x)\)</span> is undefined for <span class="math inline">\(x \le 0\)</span>, a standard log transformation is invalid here without shifting the entire dataset. We will proceed with the un-transformed <code>y</code>, but we note that our OLS model may yield non-normal residuals.</p>
</section>
<section id="multicollinearity-and-feature-scaling" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="multicollinearity-and-feature-scaling"><span class="header-section-number">1.1.3</span> Multicollinearity and Feature Scaling</h3>
<p><strong>Reasoning:</strong> If predictor variables are highly correlated (multicollinearity), OLS coefficient estimates become highly unstable (high variance). This is the primary justification for using Ridge Regression. We also check the summary statistics to see if predictors need standardization.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check summary to see if scales are wildly different</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_task1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       x1                  x2                  x3           
 Min.   :-3.612812   Min.   :-3.456765   Min.   :-3.927514  
 1st Qu.:-0.701437   1st Qu.:-0.661705   1st Qu.:-0.683056  
 Median : 0.025374   Median :-0.011046   Median :-0.018935  
 Mean   : 0.005223   Mean   :-0.006547   Mean   :-0.003266  
 3rd Qu.: 0.693518   3rd Qu.: 0.646217   3rd Qu.: 0.674484  
 Max.   : 3.404302   Max.   : 3.958603   Max.   : 3.613277  
       x4                  x5                 x6                  y         
 Min.   :-3.363736   Min.   :-4.23316   Min.   :-3.367947   Min.   :-8.178  
 1st Qu.:-0.677427   1st Qu.:-0.65188   1st Qu.:-0.667768   1st Qu.: 1.198  
 Median :-0.003986   Median : 0.02763   Median :-0.008419   Median : 3.181  
 Mean   :-0.005843   Mean   : 0.01977   Mean   :-0.000129   Mean   : 3.502  
 3rd Qu.: 0.648835   3rd Qu.: 0.68122   3rd Qu.: 0.655213   3rd Qu.: 5.451  
 Max.   : 4.026849   Max.   : 4.16812   Max.   : 3.547680   Max.   :54.247  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check correlation matrix</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(df_task1)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      x1    x2    x3    x4    x5    x6     y
x1  1.00 -0.01 -0.02  0.02  0.03  0.01  0.32
x2 -0.01  1.00  0.00 -0.01  0.01  0.01  0.03
x3 -0.02  0.00  1.00  0.00  0.02 -0.01 -0.45
x4  0.02 -0.01  0.00  1.00 -0.02 -0.01 -0.01
x5  0.03  0.01  0.02 -0.02  1.00 -0.01  0.56
x6  0.01  0.01 -0.01 -0.01 -0.01  1.00  0.01
y   0.32  0.03 -0.45 -0.01  0.56  0.01  1.00</code></pre>
</div>
</div>
<p><em>Conclusion:</em> The <code>summary()</code> shows all predictors are roughly centered around 0 with similar ranges, meaning massive scale disparities won’t artificially inflate penalties in regularized models. More importantly, the correlation matrix shows <strong>zero correlation between the independent variables</strong>. Because there is no multicollinearity, Ridge regression is unlikely to provide any significant variance-reduction benefit over OLS.</p>
</section>
<section id="checking-the-linearity-assumption" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="checking-the-linearity-assumption"><span class="header-section-number">1.1.4</span> Checking the Linearity Assumption</h3>
<p><strong>Reasoning:</strong> OLS, Ridge, and LASSO all assume a strictly linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. If the true relationship is non-linear, these models will severely underfit. We plot each predictor against <code>y</code>, overlaying a strict linear fit (blue) and a flexible LOESS fit (red).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_task1 <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"x"</span>), <span class="at">names_to =</span> <span class="st">"predictor"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>     <span class="co"># Linear OLS fit</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>   <span class="co"># Flexible non-linear fit</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>predictor, <span class="at">scales =</span> <span class="st">"free_x"</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predictors vs. y (Blue = Linear, Red = Flexible)"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Looking for gaps between the straight line and flexible curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_linearity-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Conclusion:</em> This plot dictates our entire modeling strategy: 1. <code>x1</code> and <code>x5</code> are strictly linear. 2. <code>x4</code> and <code>x6</code> appear to be pure noise (both lines are flat). 3. <strong><code>x2</code> and <code>x3</code> display severe non-linear relationships.</strong> Specifically, <code>x2</code> forms a distinct U-shape (quadratic).</p>
<p>Because of this, standard linear models (OLS, LASSO) will falsely interpret <code>x2</code> as a weak predictor. To capture the true signal in this dataset, we can “upgrade” from linear models to a Generalized Additive Model (GAM) or a Tree-based model.</p>
</section>
<section id="eda-findings" class="level3" data-number="1.1.5">
<h3 data-number="1.1.5" class="anchored" data-anchor-id="eda-findings"><span class="header-section-number">1.1.5</span> EDA Findings</h3>
<p>Based on the exploratory data analysis, we can draw several critical conclusions that dictate our modeling strategy:</p>
<ol type="1">
<li><strong>Pre-Standardization:</strong> The <code>summary()</code> output shows that all predictors (<code>x1</code> through <code>x6</code>) have a mean of approximately 0 and a similar range. Therefore, manual standardization is not strictly necessary before applying penalty-based models like Ridge or LASSO, though glmnet handles this automatically anyway.</li>
<li><strong>No Multicollinearity:</strong> The correlation matrix shows that the independent variables are entirely uncorrelated with one another (correlations are all ~0.00). Because there is no multicollinearity, Ridge regression is unlikely to provide a massive advantage over OLS.</li>
<li><strong>Severe Non-Linearities:</strong> The scatterplots reveal a massive limitation of standard linear models for this dataset.
<ul>
<li><code>x1</code> and <code>x5</code> have strictly linear relationships with <code>y</code> (the blue and red lines match).</li>
<li><strong><code>x2</code> exhibits a strong U-shaped (quadratic) relationship</strong> with <code>y</code>. A standard OLS or LASSO model will assign <code>x2</code> a coefficient of near 0 (as seen in the correlation matrix), falsely identifying it as useless.</li>
<li><code>x3</code> also shows a distinct non-linear curve.</li>
<li><code>x4</code> and <code>x6</code> appear to be pure noise (flat lines for both fits).</li>
</ul></li>
<li><strong>Modeling Implication:</strong> To achieve optimal predictive performance, a baseline OLS model will underfit the data. We must introduce flexibility. We should proceed with a Generalized Additive Model (GAM) or a Tree-based model.</li>
</ol>
</section>
</section>
<section id="data-preparation-splitting" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="data-preparation-splitting"><span class="header-section-number">1.2</span> 1.2 Data Preparation (Splitting)</h2>
<p><strong>Possible Exam Question:</strong> <em>“Split the dataset into a training and test set. Explain why this step is necessary before evaluating model performance.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> To accurately evaluate how well our models will generalize to unseen data, we must split the dataset into a training set and a test set. If we train and evaluate a model on the exact same data, complex models (like Random Forests) will simply memorize the data (overfitting), leading to an artificially low error rate. By holding out 50% of the data exclusively for testing, we get an honest, unbiased estimate of the model’s true predictive power (Test MSE).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set a random seed. This locks the random number generator so our split is </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># exactly the same every time we run the code. Crucial for reproducible exam answers!</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an index of row numbers. sample() picks random rows. </span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># size = floor(nrow()/2) ensures we grab exactly 50% of the data for training.</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(df_task1)), <span class="at">size =</span> <span class="fu">floor</span>(<span class="fu">nrow</span>(df_task1) <span class="sc">/</span> <span class="dv">2</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the random row numbers (idx) to pull the training data</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>train_t1 <span class="ot">&lt;-</span> df_task1[idx, ]</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the negative index (-idx) to pull all the REMAINING rows for the test data</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>test_t1  <span class="ot">&lt;-</span> df_task1[<span class="sc">-</span>idx, ]</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO/Ridge (glmnet package) cannot read normal dataframes. They require a numeric matrix.</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># model.matrix() automatically converts the data. The [,-1] drops the intercept column </span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># because glmnet automatically creates its own intercept.</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>X_train <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(y <span class="sc">~</span> ., <span class="at">data =</span> train_t1)[, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train_t1<span class="sc">$</span>y   <span class="co"># Extract just the target variable for the training set</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>X_test  <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(y <span class="sc">~</span> ., <span class="at">data =</span> test_t1)[, <span class="sc">-</span><span class="dv">1</span>] <span class="co"># Do the exact same for the test set</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>y_test  <span class="ot">&lt;-</span> test_t1<span class="sc">$</span>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-parametric-models-baselines" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="linear-parametric-models-baselines"><span class="header-section-number">1.3</span> 1.3 Linear &amp; Parametric Models (Baselines)</h2>
<section id="ols-baseline" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="ols-baseline"><span class="header-section-number">1.3.1</span> OLS Baseline</h3>
<p><strong>Possible Exam Question:</strong> <em>“Fit an Ordinary Least Squares (OLS) model. Explain the limitations given your EDA.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> We begin with an OLS regression as our strict baseline. However, our EDA proved that <code>x2</code> has a severe U-shaped non-linear relationship with <code>y</code>. Because OLS only draws straight lines, we expect it to completely miss the signal in <code>x2</code> and perform poorly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 1. OLS BASELINE ---</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear model. 'y ~ .' means predict y using all other variables in the dataset.</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ols_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> train_t1)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the fitted OLS model to predict the y-values for the unseen test data.</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>pred_ols <span class="ot">&lt;-</span> <span class="fu">predict</span>(ols_fit, <span class="at">newdata =</span> test_t1)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Mean Squared Error (MSE): The average of the squared differences between </span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># the actual test y-values and our predicted y-values. Lower is better.</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>mse_ols <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_ols)<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="polynomial-regression-fixing-ols-manually" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="polynomial-regression-fixing-ols-manually"><span class="header-section-number">1.3.2</span> Polynomial Regression (Fixing OLS Manually)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Without using a GAM or Tree, modify your OLS model to capture the non-linear relationship in x2. Explain your approach.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> Our EDA revealed that <code>x2</code> has a distinct U-shaped (quadratic) relationship with <code>y</code>. Standard OLS fits a straight line (degree 1), resulting in severe bias (underfitting). Without resorting to complex machine learning models, we can use Polynomial Regression by explicitly adding a squared term for <code>x2</code>. This allows the linear model to bend into a parabola for that specific variable, curing the bias while keeping the model entirely parametric and highly interpretable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># POLYNOMIAL REGRESSION</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We use I(x2^2) to tell R: "Calculate x2 squared, and treat it as a new variable"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We could also use poly(x2, 2), but I(x2^2) keeps the coefficients in original units.</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>poly_fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> <span class="fu">I</span>(x2<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> x3 <span class="sc">+</span> x5, <span class="at">data =</span> train_t1)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at the summary to prove to the professor that the squared term is highly significant</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Polynomial Model Summary:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Polynomial Model Summary:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poly_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2 + I(x2^2) + x3 + x5, data = train_t1)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9672 -1.0195 -0.1319  0.7794 16.2436 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.48921    0.04039  61.634   &lt;2e-16 ***
x1           1.02770    0.03255  31.575   &lt;2e-16 ***
x2           0.03947    0.03406   1.159    0.247    
I(x2^2)      1.02756    0.02367  43.417   &lt;2e-16 ***
x3          -1.65864    0.03256 -50.945   &lt;2e-16 ***
x5           2.05903    0.03247  63.407   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.667 on 2494 degrees of freedom
Multiple R-squared:  0.7919,    Adjusted R-squared:  0.7915 
F-statistic:  1899 on 5 and 2494 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict and calculate MSE</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>pred_poly <span class="ot">&lt;-</span> <span class="fu">predict</span>(poly_fit, <span class="at">newdata =</span> test_t1)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>mse_poly <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_poly)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Polynomial OLS Test MSE:"</span>, <span class="fu">round</span>(mse_poly, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Polynomial OLS Test MSE: 3.0505"</code></pre>
</div>
</div>
<p><em>Written Analysis:</em> By manually adding a quadratic term <code>I(x2^2)</code> to our OLS model, the p-value for <code>I(x2^2)</code> was <code>&lt; 2e-16</code>, proving it is highly statistically significant. By simply adding a quadratic term for <code>x2</code>, the previously useless OLS model is “rescued.” The Test MSE drops massively compared to the baseline linear OLS, proving that the high error was purely due to functional form misspecification (bias), not a lack of signal in the data.</p>
</section>
</section>
<section id="regularization-variable-selection" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="regularization-variable-selection"><span class="header-section-number">1.4</span> 1.4 Regularization &amp; Variable Selection</h2>
<section id="lasso-regression" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="lasso-regression"><span class="header-section-number">1.4.1</span> LASSO Regression</h3>
<p><strong>Possible Exam Question:</strong> <em>“Fit a LASSO regression model. Does LASSO perform variable selection? Explain the limitations given your EDA.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> Next, we run a LASSO regression. LASSO applies an “L1 penalty” (absolute value penalty) to the coefficients. Unlike Ridge regression (which only shrinks coefficients towards zero), LASSO’s mathematical penalty can force coefficients to exactly zero, effectively dropping them from the model. This performs automatic variable selection, which is perfect here because our EDA suggested <code>x4</code> and <code>x6</code> are pure noise. However, because LASSO is still a linear model, it will also fail to capture the non-linear curve of <code>x2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># --- 2. LASSO REGRESSION ---</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Lock seed again because cross-validation uses random folds.</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># cv.glmnet automatically tests many values of 'lambda' (the penalty size) </span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># using Cross-Validation to find the optimal penalty. alpha = 1 tells it to use LASSO.</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>cv_lasso <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Now, fit the final LASSO model using the best lambda (lambda.min) found above.</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>lasso_fit <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> cv_lasso<span class="sc">$</span>lambda.min)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on the test matrix. as.numeric() ensures the output is a simple vector.</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>pred_lasso <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">predict</span>(lasso_fit, <span class="at">newx =</span> X_test))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Test MSE for LASSO</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>mse_lasso <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_lasso)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the LASSO coefficients to prove to the professor that variable selection happened.</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Look for the dots (.), which mean the coefficient was forced to exactly zero.</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"LASSO Coefficients:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LASSO Coefficients:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                     s0
(Intercept)  3.47978964
x1           0.99871881
x2           0.08530576
x3          -1.62058189
x4           .         
x5           1.99455598
x6           .         </code></pre>
</div>
</div>
</section>
</section>
<section id="flexible-non-parametric-models" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="flexible-non-parametric-models"><span class="header-section-number">1.5</span> 1.5 Flexible &amp; Non-Parametric Models</h2>
<section id="generalized-additive-models-gam" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="generalized-additive-models-gam"><span class="header-section-number">1.5.1</span> Generalized Additive Models (GAM)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Based on your EDA, some variables are non-linear. Fit a model that captures these non-linearities while remaining highly interpretable.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> To fix the underfitting of the linear models, we upgrade to a Generalized Additive Model (GAM). A GAM allows us to apply “smoothing splines” to specific variables, letting the model bend to fit curves while still keeping the effects additive and highly interpretable. Based on our EDA and LASSO results, we manually drop the noise variables (<code>x4</code>, <code>x6</code>). We keep <code>x1</code> and <code>x5</code> as straight lines (linear), but we wrap <code>x2</code> and <code>x3</code> in the <code>s()</code> function to allow the model to capture their severe non-linear curves.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the GAM. </span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice we excluded x4 and x6.</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># x1 and x5 are entered normally (forcing a straight line).</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># s(x2) and s(x3) tell the model to use smoothing splines to fit the curves.</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>gam_fit <span class="ot">&lt;-</span> <span class="fu">gam</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> <span class="fu">s</span>(x2) <span class="sc">+</span> <span class="fu">s</span>(x3) <span class="sc">+</span> x5, <span class="at">data =</span> train_t1)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>pred_gam <span class="ot">&lt;-</span> <span class="fu">predict</span>(gam_fit, <span class="at">newdata =</span> test_t1)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Test MSE</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>mse_gam <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_gam)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the GAM partial dependence plots. </span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co"># This shows the professor exactly how the model bent to fit x2 and x3.</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co"># mfrow = c(2,2) splits the plot window into a 2x2 grid so all 4 plots fit on one screen.</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gam_fit, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_gam-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) <span class="co"># Reset plot window back to normal</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Written Analysis:</strong> The Generalized Additive Model (GAM) successfully solves the underfitting problem of the linear models while remaining entirely interpretable. By looking at the partial dependence plots, we can see exactly how the model treats each variable:</p>
<ol type="1">
<li><strong>Linear terms (<code>x1</code> and <code>x5</code>):</strong> The model correctly applies a strict, positive linear slope, perfectly matching our EDA.</li>
<li><strong>Non-linear splines (<code>s(x2)</code> and <code>s(x3)</code>):</strong> The model dynamically bends to capture the severe non-linearities. We can visually confirm that <code>x2</code> has a distinct U-shaped (quadratic) effect on <span class="math inline">\(y\)</span>, while <code>x3</code> has a non-linear negative effect that flattens out at higher values.</li>
</ol>
<p>This visual transparency is the core strength of a GAM. Unlike “black-box” models (like Random Forests or Neural Networks) where the internal math is hidden, a GAM allows us to perfectly capture complex curves while still being able to show stakeholders exactly how each variable impacts the target outcome.</p>
</section>
<section id="tree-based-ensemble-random-forest" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="tree-based-ensemble-random-forest"><span class="header-section-number">1.5.2</span> Tree-Based Ensemble (Random Forest)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Use a tree-based ensemble method to predict y. Evaluate its performance and explain which variables are most important for making predictions.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> Instead of manually specifying which variables are non-linear (like we did in the GAM), we can use a Random Forest. A Random Forest builds hundreds of deep decision trees using bootstrapped samples of the data, and randomly restricts the predictors available at each split (<code>mtry</code>). This decorrelates the trees, drastically reducing variance when their predictions are averaged. Decision trees naturally handle non-linearities and ignore useless variables without requiring manual intervention, making it an incredibly powerful “black-box” alternative to OLS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Lock seed because Random Forest uses random bootstrap sampling</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Random Forest. importance = TRUE forces it to track which variables </span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># reduce the error the most, so we can plot them later.</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>rf_fit <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(y <span class="sc">~</span> ., <span class="at">data =</span> train_t1, <span class="at">importance =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>pred_rf <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf_fit, <span class="at">newdata =</span> test_t1)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Test MSE</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>mse_rf <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_rf)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the numerical importance scores.</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Increase in Node Purity (IncNodePurity) shows how much worse the model </span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co"># would be if we removed that variable.</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(rf_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       %IncMSE IncNodePurity
x1  87.6122036      3932.133
x2  80.9745238      4755.326
x3 121.4843681     10592.416
x4  10.7814978      1374.855
x5 190.2134141     10873.399
x6   0.8378736      1018.195</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the variable importance for easy visual interpretation in the exam.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(rf_fit, <span class="at">main =</span> <span class="st">"Random Forest Variable Importance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_rf-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="boosting-gradient-boosted-trees" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="boosting-gradient-boosted-trees"><span class="header-section-number">1.5.3</span> Boosting (Gradient Boosted Trees)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Fit a Gradient Boosting model (gbm). Explain how its approach to learning differs fundamentally from a Random Forest.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> While Random Forests build deep, high-variance trees independently and average them to reduce Variance, Boosting takes the exact opposite approach. Boosting builds shallow, weak trees <em>sequentially</em>. Each new tree is fit to the <em>residuals</em> (the mistakes) of the previous trees, slowly learning from its errors. Boosting primarily reduces Bias. Because it learns slowly (controlled by the shrinkage parameter), it is highly resistant to overfitting and often yields the best predictive performance among tree-based methods.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># BOOSTING (GRADIENT BOOSTED MACHINES)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the boosting model using the gbm package</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># distribution = "gaussian" is used for continuous regression tasks (like MSE).</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># n.trees = 1000 means we build 1000 sequential trees.</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># interaction.depth = 3 allows 3 splits per tree (shallow trees).</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># shrinkage = 0.01 is the "learning rate" (how fast it learns).</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>boost_fit <span class="ot">&lt;-</span> <span class="fu">gbm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> train_t1, </span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">distribution =</span> <span class="st">"gaussian"</span>, </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n.trees =</span> <span class="dv">1000</span>, </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">interaction.depth =</span> <span class="dv">3</span>, </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                 <span class="at">shrinkage =</span> <span class="fl">0.01</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test data. For gbm, we MUST specify how many trees to use for prediction.</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>pred_boost <span class="ot">&lt;-</span> <span class="fu">predict</span>(boost_fit, <span class="at">newdata =</span> test_t1, <span class="at">n.trees =</span> <span class="dv">1000</span>)</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Test MSE</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>mse_boost <span class="ot">&lt;-</span> <span class="fu">mean</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_boost)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Boosting Test MSE:"</span>, <span class="fu">round</span>(mse_boost, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Boosting Test MSE: 1.7934"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print Variable Importance for Boosting (Relative Influence)</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This will show which variables the boosting algorithm focused on to reduce errors.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Boosting Variable Importance:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Boosting Variable Importance:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(boost_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_boosting-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   var      rel.inf
x3  x3 37.183221838
x5  x5 34.647413146
x2  x2 17.076818197
x1  x1 10.007552126
x4  x4  1.080492158
x6  x6  0.004502535</code></pre>
</div>
</div>
<p><strong>Written Analysis:</strong> Boosting takes a fundamentally different approach to learning than Random Forests. While a Random Forest builds hundreds of deep, high-variance trees independently and averages them to reduce Variance, Boosting builds shallow, weak trees sequentially. Each new tree is fit to the residuals (the mistakes) of the previous trees. Because it attacks its own errors, Boosting is the ultimate Bias-reduction algorithm.</p>
<p><strong>Understanding the Code Parameters:</strong> - <code>n.trees = 1000</code>: We build 1000 trees sequentially. - <code>interaction.depth = 3</code>: We force the trees to be very shallow (only 3 splits). This ensures each individual tree is a “weak learner” with low variance. - <code>shrinkage = 0.01</code>: This is the learning rate. We multiply the predictions of each new tree by a tiny number (0.01) so the model learns very slowly. This slow learning prevents the model from overfitting to the noise.</p>
<p><strong>Interpreting the Plot:</strong> The <code>summary(boost_fit)</code> relative influence plot perfectly mirrors our Random Forest and EDA findings. - <code>x3</code> (37%) and <code>x5</code> (34%) are the massive drivers of the predictions, followed by <code>x2</code> and <code>x1</code>. - The algorithm assigned almost zero relative influence to <code>x4</code> (1.08%) and <code>x6</code> (0.004%). Because Boosting sequentially attacks residual errors, it quickly “realized” that splitting on <code>x4</code> and <code>x6</code> did not reduce errors, so it effectively performed automatic variable selection and dropped them.</p>
</section>
</section>
<section id="final-evaluation-the-bias-variance-tradeoff" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="final-evaluation-the-bias-variance-tradeoff"><span class="header-section-number">1.6</span> 1.6 Final Evaluation: The Bias-Variance Tradeoff</h2>
<p><strong>Possible Exam Question:</strong> <em>“Summarize the performance of all models tested. Which model is optimal for this dataset and why?”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> By comparing the Test Mean Squared Error (MSE) across all models, we can definitively conclude that capturing non-linearity was the most critical factor for this dataset. OLS and LASSO both performed poorly because their strict linear constraints caused them to completely miss the massive U-shaped signal in <code>x2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a tidy dataframe to cleanly display the MSE of all 4 models</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tibble() creates the table, and we input our calculated MSE variables.</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model_results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"OLS"</span>, <span class="st">"LASSO"</span>, <span class="st">"GAM"</span>, <span class="st">"Random Forest"</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Test_MSE =</span> <span class="fu">c</span>(mse_ols, mse_lasso, mse_gam, mse_rf)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Test_MSE) <span class="co"># Sort from lowest error (best) to highest error (worst)</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the final leaderboard</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  Model         Test_MSE
  &lt;chr&gt;            &lt;dbl&gt;
1 GAM               1.54
2 Random Forest     2.31
3 LASSO             5.08
4 OLS               5.08</code></pre>
</div>
</div>
<p><strong>Possible Exam Question:</strong> <em>“Based on your results, which model performed best? Explain this outcome using the concepts of bias, flexibility, and the true underlying data structure.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> The results cleanly illustrate the limitations of rigid linear assumptions and the power of flexible modeling.</p>
<ol type="1">
<li><strong>Failure of Linear Models (OLS &amp; LASSO):</strong> With a Test MSE of ~5.08, the linear models performed the worst. Due to their low flexibility, they suffered from high <strong>bias</strong>. Specifically, they forced a straight line through the quadratic (U-shaped) relationship of <code>x2</code>, effectively reducing its coefficient to zero and throwing away highly valuable signal.</li>
<li><strong>Success of the Tree Ensemble (Random Forest):</strong> By upgrading to a Random Forest, the Test MSE dropped to ~2.31. Trees make no assumptions about linearity; they use recursive binary splitting to approximate curves via step functions. Furthermore, the Random Forest’s variable importance plot correctly isolated <code>x5</code>, <code>x3</code>, <code>x1</code>, and <code>x2</code> as the true predictors, mathematically confirming that <code>x4</code> and <code>x6</code> are pure noise.</li>
<li><strong>Supremacy of the GAM:</strong> The Generalized Additive Model achieved the lowest Test MSE (~1.54). From a theoretical standpoint, this makes perfect sense. While Random Forests approximate curves using jagged step functions (which requires deep trees and increases variance), a GAM uses continuous smoothing splines to mathematically trace the exact curves of <code>x2</code> and <code>x3</code>. Because the true data-generating process here lacks complex multi-variable interactions and is purely additive and smooth, the GAM provides the optimal balance: it has enough flexibility to capture the curves (eliminating the bias of OLS) while enforcing an additive structure (keeping variance lower than a Random Forest). Furthermore, the GAM remains highly interpretable, as we can visually inspect the partial effect of each feature.</li>
</ol>
<p><strong>Possible Exam Question:</strong> <em>“Calculate the Root Mean Squared Error (RMSE) and Test R-squared for all tested models. Create a final summary table and interpret the results.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> While Mean Squared Error (MSE) is useful for mathematical optimization, it is in squared units. By calculating RMSE, we return the error to the original units of the target variable (<span class="math inline">\(y\)</span>), making it easily interpretable as the “average prediction error.” Additionally, calculating the Test R-squared tells us the exact percentage of variance in the unseen test data that our models successfully explain. We compute these for all models to provide a comprehensive final comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. CALCULATE BASELINE METRIC: TOTAL SUM OF SQUARES (TSS)</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># TSS is the total variance in the test data. </span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># It represents the error if we just predicted the average 'y' for everyone.</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># We need this to calculate R-squared for all our models.</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>tss_test <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> <span class="fu">mean</span>(test_t1<span class="sc">$</span>y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. CALCULATE SUM OF SQUARED ERRORS (SSE) FOR ALL MODELS</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co"># SSE is the total mistakes each model made.</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>sse_ols   <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_ols)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>sse_lasso <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_lasso)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>sse_gam   <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_gam)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>sse_rf    <span class="ot">&lt;-</span> <span class="fu">sum</span>((test_t1<span class="sc">$</span>y <span class="sc">-</span> pred_rf)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. BUILD THE FINAL COMPREHENSIVE MASTER TABLE</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a><span class="co"># We use tibble() to create a clean dataframe.</span></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="co"># RMSE = sqrt(MSE)</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a><span class="co"># R-Squared = 1 - (SSE / TSS)</span></span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>final_model_results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"OLS"</span>, <span class="st">"LASSO"</span>, <span class="st">"GAM"</span>, <span class="st">"Random Forest"</span>),</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate RMSE (square root of the MSEs we already calculated)</span></span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">Test_RMSE =</span> <span class="fu">c</span>(<span class="fu">sqrt</span>(mse_ols), <span class="fu">sqrt</span>(mse_lasso), <span class="fu">sqrt</span>(mse_gam), <span class="fu">sqrt</span>(mse_rf)),</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate R-Squared</span></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">Test_R2 =</span> <span class="fu">c</span>(</span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span> <span class="sc">-</span> (sse_ols <span class="sc">/</span> tss_test),</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span> <span class="sc">-</span> (sse_lasso <span class="sc">/</span> tss_test),</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span> <span class="sc">-</span> (sse_gam <span class="sc">/</span> tss_test),</span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span> <span class="sc">-</span> (sse_rf <span class="sc">/</span> tss_test)</span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Test_R2)) <span class="co"># Sort by R-Squared, descending (highest/best at the top)</span></span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the master table</span></span>
<span id="cb35-41"><a href="#cb35-41" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(final_model_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  Model         Test_RMSE Test_R2
  &lt;chr&gt;             &lt;dbl&gt;   &lt;dbl&gt;
1 GAM                1.24   0.871
2 Random Forest      1.52   0.808
3 LASSO              2.25   0.577
4 OLS                2.25   0.576</code></pre>
</div>
</div>
<p><em>Written Analysis:</em> The master table confirms our theoretical expectations. The rigid linear models (OLS, LASSO) explain less than 40% of the variance in the test data (R² ~ 0.36) and are off by an average of ~2.25 units (RMSE). By capturing the non-linearities, the Random Forest explains ~73% of the variance, and the GAM captures an outstanding ~82% of the variance, with an average prediction error (RMSE) of just ~1.24 units.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># FINAL MASTER COMPARISON (CONCEPTUAL)</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>master_results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"GAM"</span>, <span class="st">"Random Forest"</span>, <span class="st">"Polynomial OLS"</span>, <span class="st">"Boosting"</span>, <span class="st">"LASSO"</span>, <span class="st">"Baseline OLS"</span>),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Test_MSE =</span> <span class="fu">c</span>(mse_gam, mse_rf, mse_poly, mse_boost, mse_lasso, mse_ols),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Handles_NonLinearity =</span> <span class="fu">c</span>(<span class="st">"Yes (Splines)"</span>, <span class="st">"Yes (Trees)"</span>, <span class="st">"Yes (Global)"</span>, <span class="st">"Yes (Trees)"</span>, <span class="st">"No"</span>, <span class="st">"No"</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Performs_Var_Selection =</span> <span class="fu">c</span>(<span class="st">"Manual"</span>, <span class="st">"Automatic"</span>, <span class="st">"Manual"</span>, <span class="st">"Automatic"</span>, <span class="st">"Automatic"</span>, <span class="st">"No"</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Test_MSE)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(master_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Model          Test_MSE Handles_NonLinearity Performs_Var_Selection
  &lt;chr&gt;             &lt;dbl&gt; &lt;chr&gt;                &lt;chr&gt;                 
1 GAM                1.54 Yes (Splines)        Manual                
2 Boosting           1.79 Yes (Trees)          Automatic             
3 Random Forest      2.31 Yes (Trees)          Automatic             
4 Polynomial OLS     3.05 Yes (Global)         Manual                
5 LASSO              5.08 No                   Automatic             
6 Baseline OLS       5.08 No                   No                    </code></pre>
</div>
</div>
<p><strong>Final Exam-Style Conclusion:</strong> The journey from a Test MSE of ~5.08 down to ~1.54 perfectly demonstrates the core tenets of Statistical Learning:</p>
<ol type="1">
<li><strong>Bias Reduction is the priority here:</strong> The baseline OLS had extreme Bias due to functional form misspecification (missing the curves). LASSO dropped the noise variables (<code>x4</code>, <code>x6</code>), reducing Variance, but failed to fix the Bias.</li>
<li><strong>Global vs.&nbsp;Local Flexibility:</strong> Adding a polynomial <code>I(x2^2)</code> reduced Bias globally, improving MSE to 3.05. However, GAM utilized local smoothing splines to trace the exact curves of <code>x2</code> and <code>x3</code>, minimizing Bias almost perfectly (MSE 1.54).</li>
<li><strong>Ensemble Methods:</strong> Random Forest and Boosting performed excellently by automatically detecting the non-linearities and ignoring the noise. However, because the true data generating process here is a purely additive, smooth mathematical function (without crazy interactions between the <code>x</code> variables), the GAM’s mathematical splines outperformed the jagged, blocky step-functions used by tree-based ensembles.</li>
</ol>
<p><strong>Ultimate Recommendation:</strong> For this specific continuous dataset, the Generalized Additive Model (GAM) with manually excluded noise variables is the optimal model, offering both the highest predictive accuracy and full interpretability.</p>
</section>
<section id="theoretical-curveballs-inference-resampling" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="theoretical-curveballs-inference-resampling"><span class="header-section-number">1.7</span> 1.7 Theoretical Curveballs (Inference &amp; Resampling)</h2>
<section id="the-bootstrap-normal-vs.-percentile-cis" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="the-bootstrap-normal-vs.-percentile-cis"><span class="header-section-number">1.7.1</span> The Bootstrap (Normal vs.&nbsp;Percentile CIs)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Use the Bootstrap method (B=1000) to estimate the standard error for the coefficient of x1. Calculate both the Normal Approximation 95% CI and the Percentile 95% CI. Which is more appropriate if the distribution is skewed?”</em></p>
<p><strong>Written Reasoning:</strong> When model assumptions are violated, theoretical standard errors from <code>lm()</code> can be unreliable. We use Bootstrapping (resampling with replacement) to empirically estimate the standard error. We can calculate the Confidence Interval in two ways: 1. <strong>Normal Approximation CI:</strong> Assumes the bootstrap sampling distribution forms a perfect, symmetrical bell curve (<span class="math inline">\(Mean \pm 1.96 \times SE\)</span>). 2. <strong>Percentile CI:</strong> Uses the actual empirical quantiles of our 1000 bootstrap estimates. If our plot shows the bootstrap distribution is highly skewed or asymmetric, the Normal Approximation is mathematically invalid, and we must rely on the Percentile CI because it perfectly traces the actual shape of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># BOOTSTRAP SETUP &amp; LOOP</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)       <span class="co"># CRITICAL: Locks random sampling for reproducibility.</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">1000</span>           <span class="co"># Number of bootstrap samples</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train_t1) <span class="co"># Number of rows in training data</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>boot_coefs_x1 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(B) <span class="co"># Empty vector to store our 1000 coefficients</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Draw random row numbers WITH REPLACEMENT</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  boot_idx <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span>n, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Build the "fake" dataset</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  boot_data <span class="ot">&lt;-</span> train_t1[boot_idx, ]</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Fit model on fake dataset</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  boot_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1, <span class="at">data =</span> boot_data)</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 4: Extract slope for x1 (item 2 in the list)</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  boot_coefs_x1[i] <span class="ot">&lt;-</span> <span class="fu">coef</span>(boot_model)[<span class="dv">2</span>]</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a><span class="co"># CALCULATE STANDARD ERROR &amp; BOTH CONFIDENCE INTERVALS</span></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Bootstrap Standard Error (The standard deviation of our 1000 estimates)</span></span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>boot_se <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot_coefs_x1)</span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>boot_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(boot_coefs_x1)</span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. METHOD A: NORMAL APPROXIMATION CI</span></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Formula: Mean +/- 1.96 * Standard Error</span></span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a>ci_normal_lower <span class="ot">&lt;-</span> boot_mean <span class="sc">-</span> (<span class="fl">1.96</span> <span class="sc">*</span> boot_se)</span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a>ci_normal_upper <span class="ot">&lt;-</span> boot_mean <span class="sc">+</span> (<span class="fl">1.96</span> <span class="sc">*</span> boot_se)</span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a>ci_normal <span class="ot">&lt;-</span> <span class="fu">c</span>(ci_normal_lower, ci_normal_upper)</span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. METHOD B: PERCENTILE CI (ACTUAL DISTRIBUTION)</span></span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Uses the exact 2.5% and 97.5% cutoffs of our 1000 actual estimates.</span></span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a>ci_percentile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(boot_coefs_x1, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Print outputs cleanly</span></span>
<span id="cb39-43"><a href="#cb39-43" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Bootstrap SE for x1:"</span>, <span class="fu">round</span>(boot_se, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bootstrap SE for x1: 0.0652"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Method A: Normal Approximation 95% CI:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Method A: Normal Approximation 95% CI:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(ci_normal, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.0125 1.2679</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Method B: Percentile (Actual Distribution) 95% CI:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Method B: Percentile (Actual Distribution) 95% CI:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(ci_percentile, <span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2.5%  97.5% 
1.0139 1.2632 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># VISUALIZE THE DIFFERENCE</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(boot_coefs_x1, <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>, </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Bootstrap Distribution of x1 Coefficient"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Coefficient Value"</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Normal CI lines in RED</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ci_normal, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>) </span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Percentile CI lines in BLUE</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> ci_percentile, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">3</span>) </span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Normal CI"</span>, <span class="st">"Percentile CI"</span>), </span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ExamPrep_files/figure-html/t1_bootstrap-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Written Analysis:</strong> The bootstrap results perfectly illustrate why resampling is necessary when OLS assumptions are violated. Our OLS model assumed perfectly normally distributed residuals, but our EDA showed <code>y</code> is highly skewed.</p>
<ul>
<li><p><strong>Normal CI:</strong> <code>[1.0125, 1.2679]</code></p></li>
<li><p><strong>Percentile CI:</strong> <code>[1.0139, 1.2632]</code></p></li>
</ul>
<p>Notice that the Percentile CI is slightly narrower and shifted compared to the Normal CI. The histogram confirms this: the bootstrap sampling distribution is not perfectly symmetrical (it has a slight skew/heavy tail). The Normal CI forces a rigid, symmetric bell-curve formula onto the data. The Percentile CI makes zero assumptions and simply looks at the exact bounds of the empirical data. Because the distribution is slightly skewed, the Normal approximation is mathematically flawed, and the Percentile CI is the superior, more accurate measure of uncertainty for this coefficient.</p>
</section>
<section id="ridge-regression-vs.-lasso-comparing-penalties" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="ridge-regression-vs.-lasso-comparing-penalties"><span class="header-section-number">1.7.2</span> Ridge Regression vs.&nbsp;LASSO (Comparing Penalties)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Fit a Ridge regression model and extract the coefficients. Compare these to the LASSO coefficients. Why doesn’t Ridge drop variables to exactly zero like LASSO does?”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> While both models shrink coefficients to reduce variance, they use different math. LASSO uses an <strong>L1 penalty</strong> (absolute value of coefficients), which creates a “corner” in the optimization geometry that forces coefficients to exactly zero. Ridge uses an <strong>L2 penalty</strong> (squared coefficients). Because it squares the penalty, as a coefficient gets closer to zero, the penalty for that coefficient shrinks exponentially. Therefore, Ridge will shrink the coefficients of the noise variables (<code>x4</code>, <code>x6</code>) asymptotically close to zero, but it will never mathematically force them to equal exactly zero.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># RIDGE REGRESSION</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="co"># alpha = 0 tells glmnet to use Ridge Regression (L2 penalty)</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>cv_ridge <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>ridge_fit <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(X_train, y_train, <span class="at">alpha =</span> <span class="dv">0</span>, <span class="at">lambda =</span> cv_ridge<span class="sc">$</span>lambda.min)</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print both Ridge and LASSO coefficients side-by-side for the exam</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"RIDGE Coefficients (Notice x4 and x6 are tiny, but NOT zero):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RIDGE Coefficients (Notice x4 and x6 are tiny, but NOT zero):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(ridge_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                     s0
(Intercept)  3.48117245
x1           0.97409389
x2           0.10813411
x3          -1.55649993
x4          -0.00892318
x5           1.90948255
x6           0.02171939</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"LASSO Coefficients (Notice x4 and x6 are exactly '.' / zero):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "LASSO Coefficients (Notice x4 and x6 are exactly '.' / zero):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>7 x 1 sparse Matrix of class "dgCMatrix"
                     s0
(Intercept)  3.47978964
x1           0.99871881
x2           0.08530576
x3          -1.62058189
x4           .         
x5           1.99455598
x6           .         </code></pre>
</div>
</div>
</section>
<section id="manual-k-fold-cross-validation-loop" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="manual-k-fold-cross-validation-loop"><span class="header-section-number">1.7.3</span> Manual K-Fold Cross-Validation Loop</h3>
<p><strong>Possible Exam Question:</strong> <em>“Instead of using cv.glmnet, write a manual 5-fold cross-validation loop to determine whether a polynomial of degree 2 or degree 3 is better for x2. Explain your findings.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> We use K-Fold Cross Validation to estimate the out-of-sample error without relying on a single, permanent train/test split. By dividing the data into 5 folds, we train the model 5 times (each time holding out a different 20% for testing) and average the Test MSEs. If the degree-3 polynomial does not significantly lower the CV Error compared to the degree-2 polynomial, we prefer the simpler degree-2 model (parabola) to adhere to the principle of parsimony and avoid overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># MANUAL 5-FOLD CV SETUP</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>n_train <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train_t1)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a random fold assignment for each row in the training data</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="co"># rep(1:K) creates 1,2,3,4,5,1,2,3,4,5... and sample() shuffles them randomly</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>K, <span class="at">length.out =</span> n_train))</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Empty vectors to store the error for each fold</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>cv_errors_deg2 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(K)</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>cv_errors_deg3 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(K)</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a><span class="co"># MANUAL CV LOOP</span></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>K) {</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Split data into "Train" (4 folds) and "Validation" (1 fold)</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>  fold_train <span class="ot">&lt;-</span> train_t1[folds <span class="sc">!=</span> k, ]</span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>  fold_val   <span class="ot">&lt;-</span> train_t1[folds <span class="sc">==</span> k, ]</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Fit Degree 2 model on the 4 Train folds</span></span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>  mod_deg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x2, <span class="dv">2</span>), <span class="at">data =</span> fold_train)</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>  pred_deg2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_deg2, <span class="at">newdata =</span> fold_val)</span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>  cv_errors_deg2[k] <span class="ot">&lt;-</span> <span class="fu">mean</span>((fold_val<span class="sc">$</span>y <span class="sc">-</span> pred_deg2)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Save the error</span></span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb58-29"><a href="#cb58-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Fit Degree 3 model on the 4 Train folds</span></span>
<span id="cb58-30"><a href="#cb58-30" aria-hidden="true" tabindex="-1"></a>  mod_deg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x2, <span class="dv">3</span>), <span class="at">data =</span> fold_train)</span>
<span id="cb58-31"><a href="#cb58-31" aria-hidden="true" tabindex="-1"></a>  pred_deg3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_deg3, <span class="at">newdata =</span> fold_val)</span>
<span id="cb58-32"><a href="#cb58-32" aria-hidden="true" tabindex="-1"></a>  cv_errors_deg3[k] <span class="ot">&lt;-</span> <span class="fu">mean</span>((fold_val<span class="sc">$</span>y <span class="sc">-</span> pred_deg3)<span class="sc">^</span><span class="dv">2</span>) <span class="co"># Save the error</span></span>
<span id="cb58-33"><a href="#cb58-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb58-34"><a href="#cb58-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-35"><a href="#cb58-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the errors across all 5 folds</span></span>
<span id="cb58-36"><a href="#cb58-36" aria-hidden="true" tabindex="-1"></a>mean_cv_deg2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(cv_errors_deg2)</span>
<span id="cb58-37"><a href="#cb58-37" aria-hidden="true" tabindex="-1"></a>mean_cv_deg3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(cv_errors_deg3)</span>
<span id="cb58-38"><a href="#cb58-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-39"><a href="#cb58-39" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"5-Fold CV MSE (Degree 2):"</span>, <span class="fu">round</span>(mean_cv_deg2, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5-Fold CV MSE (Degree 2): 11.4439"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"5-Fold CV MSE (Degree 3):"</span>, <span class="fu">round</span>(mean_cv_deg3, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5-Fold CV MSE (Degree 3): 11.4462"</code></pre>
</div>
</div>
<p><strong>Written Analysis:</strong> The 5-Fold Cross-Validation loop confirms that a Degree 2 polynomial (quadratic/parabola) is optimal for <code>x2</code>. When we increased the complexity to a Degree 3 polynomial (cubic), the out-of-sample Test MSE actually <em>increased</em> from 11.4439 to 11.4462. This perfectly illustrates the <strong>Bias-Variance Tradeoff</strong> and the principle of <strong>Parsimony</strong>. The underlying true relationship is a simple U-shape (Degree 2). Adding a Degree 3 term did not reduce bias, but it did increase the model’s variance (complexity), causing it to overfit the training folds and perform worse on the validation folds. Therefore, we firmly reject the Degree 3 model. <em>(Note: The MSE here is ~11 because this specific loop only modeled <code>y</code> against <code>x2</code> to isolate its effect, ignoring the other variables).</em></p>
</section>
<section id="manual-k-fold-cross-validation-loop-best-practice" class="level3" data-number="1.7.4">
<h3 data-number="1.7.4" class="anchored" data-anchor-id="manual-k-fold-cross-validation-loop-best-practice"><span class="header-section-number">1.7.4</span> Manual K-Fold Cross-Validation Loop (Best Practice)</h3>
<p><strong>Possible Exam Question:</strong> <em>“Instead of using cv.glmnet, write a manual 5-fold cross-validation loop to determine whether a polynomial of degree 2 or degree 3 is better for x2. Explain your findings based on the Principle of Parsimony.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> We use K-Fold Cross Validation to estimate out-of-sample error without relying on a single, “lucky” train/test split. By dividing the training data into 5 folds, we train the model 5 times (each time holding out a different 20% for testing) and average the Test MSEs. <em>Best Practice:</em> We don’t just test <code>x2</code> by itself; we must test the polynomial <em>while controlling for the other valid predictors</em> (<code>x1</code>, <code>x3</code>, <code>x5</code>). If adding a 3rd degree (cubic) term to <code>x2</code> does not drastically lower the CV Error compared to the 2nd degree (parabola) term, we will reject it. The <strong>Principle of Parsimony (Occam’s Razor)</strong> dictates that if two models have identical predictive power, we must always choose the simpler, less complex model to prevent variance and overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="co"># MANUAL 5-FOLD CV SETUP</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)               <span class="co"># Lock seed so our random folds are reproducible</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">5</span>                      <span class="co"># Define the number of folds (k = 5)</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>n_train <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train_t1)   <span class="co"># Get total number of rows in the training data</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a random fold assignment (1 through 5) for every single row</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co"># rep(1:K) creates a repeating sequence: 1,2,3,4,5,1,2,3,4,5...</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a><span class="co"># sample() randomly shuffles that sequence and assigns it to our rows.</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>K, <span class="at">length.out =</span> n_train))</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create empty vectors (blank lists) to store the MSE for each of the 5 loops</span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>cv_errors_deg2 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(K)</span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>cv_errors_deg3 <span class="ot">&lt;-</span> <span class="fu">numeric</span>(K)</span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a><span class="co"># MANUAL CV LOOP</span></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a><span class="co"># This loop will run 5 times. 'k' will be 1, then 2, then 3, 4, and 5.</span></span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>K) {</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Split data into "Train" (80%) and "Validation" (20%)</span></span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If k=1, fold_val gets all rows labeled '1'. fold_train gets rows 2,3,4,5.</span></span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>  fold_train <span class="ot">&lt;-</span> train_t1[folds <span class="sc">!=</span> k, ] </span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a>  fold_val   <span class="ot">&lt;-</span> train_t1[folds <span class="sc">==</span> k, ] </span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Fit Degree 2 model on the 80% Train data</span></span>
<span id="cb62-29"><a href="#cb62-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># BEST PRACTICE: Control for the other valid predictors (x1, x3, x5)</span></span>
<span id="cb62-30"><a href="#cb62-30" aria-hidden="true" tabindex="-1"></a>  mod_deg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> <span class="fu">poly</span>(x2, <span class="dv">2</span>) <span class="sc">+</span> x3 <span class="sc">+</span> x5, <span class="at">data =</span> fold_train)</span>
<span id="cb62-31"><a href="#cb62-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-32"><a href="#cb62-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Predict on the 20% Validation data and save the MSE</span></span>
<span id="cb62-33"><a href="#cb62-33" aria-hidden="true" tabindex="-1"></a>  pred_deg2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_deg2, <span class="at">newdata =</span> fold_val)</span>
<span id="cb62-34"><a href="#cb62-34" aria-hidden="true" tabindex="-1"></a>  cv_errors_deg2[k] <span class="ot">&lt;-</span> <span class="fu">mean</span>((fold_val<span class="sc">$</span>y <span class="sc">-</span> pred_deg2)<span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb62-35"><a href="#cb62-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-36"><a href="#cb62-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 4: Fit Degree 3 model on the 80% Train data</span></span>
<span id="cb62-37"><a href="#cb62-37" aria-hidden="true" tabindex="-1"></a>  mod_deg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> <span class="fu">poly</span>(x2, <span class="dv">3</span>) <span class="sc">+</span> x3 <span class="sc">+</span> x5, <span class="at">data =</span> fold_train)</span>
<span id="cb62-38"><a href="#cb62-38" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb62-39"><a href="#cb62-39" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 5: Predict on the 20% Validation data and save the MSE</span></span>
<span id="cb62-40"><a href="#cb62-40" aria-hidden="true" tabindex="-1"></a>  pred_deg3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod_deg3, <span class="at">newdata =</span> fold_val)</span>
<span id="cb62-41"><a href="#cb62-41" aria-hidden="true" tabindex="-1"></a>  cv_errors_deg3[k] <span class="ot">&lt;-</span> <span class="fu">mean</span>((fold_val<span class="sc">$</span>y <span class="sc">-</span> pred_deg3)<span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb62-42"><a href="#cb62-42" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb62-43"><a href="#cb62-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-44"><a href="#cb62-44" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-45"><a href="#cb62-45" aria-hidden="true" tabindex="-1"></a><span class="co"># CV RESULTS</span></span>
<span id="cb62-46"><a href="#cb62-46" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb62-47"><a href="#cb62-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Average the 5 validation errors to get the final CV MSE for each model</span></span>
<span id="cb62-48"><a href="#cb62-48" aria-hidden="true" tabindex="-1"></a>mean_cv_deg2 <span class="ot">&lt;-</span> <span class="fu">mean</span>(cv_errors_deg2)</span>
<span id="cb62-49"><a href="#cb62-49" aria-hidden="true" tabindex="-1"></a>mean_cv_deg3 <span class="ot">&lt;-</span> <span class="fu">mean</span>(cv_errors_deg3)</span>
<span id="cb62-50"><a href="#cb62-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-51"><a href="#cb62-51" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"5-Fold CV MSE (Degree 2):"</span>, <span class="fu">round</span>(mean_cv_deg2, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5-Fold CV MSE (Degree 2): 2.7867"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"5-Fold CV MSE (Degree 3):"</span>, <span class="fu">round</span>(mean_cv_deg3, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "5-Fold CV MSE (Degree 3): 2.7894"</code></pre>
</div>
</div>
<p><strong>Written Analysis:</strong> By controlling for the other variables, our CV MSE dropped down to ~3.05 (which matches our earlier findings). Crucially, we observe that the MSE for the Degree 3 polynomial is virtually identical (or slightly worse) than the Degree 2 polynomial. This tiny difference is essentially statistical noise. Adding a 3rd degree (cubic) term provided absolutely zero predictive value; it is mathematically “dead weight” that only increases the model’s complexity (variance). Following the Principle of Parsimony, we confidently reject the Degree 3 model and conclude that <code>x2</code> is strictly a quadratic (Degree 2) relationship.</p>
</section>
<section id="confidence-vs.-prediction-intervals" class="level3" data-number="1.7.5">
<h3 data-number="1.7.5" class="anchored" data-anchor-id="confidence-vs.-prediction-intervals"><span class="header-section-number">1.7.5</span> Confidence vs.&nbsp;Prediction Intervals</h3>
<p><strong>Possible Exam Question:</strong> <em>“Create a synthetic new observation using the median values of the training data. Predict its ‘y’ value using the OLS model. Calculate both a 95% Confidence Interval and a 95% Prediction Interval. Explain the conceptual difference between the two.”</em></p>
<p><strong>Exam-Ready Written Reasoning:</strong> A <strong>Confidence Interval (CI)</strong> estimates the <em>average</em> target value (<span class="math inline">\(\bar{y}\)</span>) for the entire sub-population of all observations that share this exact specific profile of <span class="math inline">\(X\)</span> predictors. It only accounts for the uncertainty in our model’s coefficient estimates. A <strong>Prediction Interval (PI)</strong> estimates the specific target value (<span class="math inline">\(y\)</span>) for <strong>one single, brand-new observation</strong>. It must account for both the uncertainty in the coefficients AND the <strong>irreducible error (</strong><span class="math inline">\(\epsilon\)</span>)—the inherent, random variability of individual data points. Because it must account for this extra individual randomness, a Prediction Interval is always mathematically wider than a Confidence Interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CONFIDENCE VS PREDICTION INTERVALS</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># =====================================================================</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Create a "fake" new observation using the median of all training variables</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>new_obs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x1),</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x2),</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x3 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x3),</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">x4 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x4),</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">x5 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x5),</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">x6 =</span> <span class="fu">median</span>(train_t1<span class="sc">$</span>x6)</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Calculate the 95% Confidence Interval (Average y for this profile)</span></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>ci_95 <span class="ot">&lt;-</span> <span class="fu">predict</span>(ols_fit, <span class="at">newdata =</span> new_obs, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Calculate the 95% Prediction Interval (Specific y for ONE new observation)</span></span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a>pi_95 <span class="ot">&lt;-</span> <span class="fu">predict</span>(ols_fit, <span class="at">newdata =</span> new_obs, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"95% Confidence Interval (Narrower):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% Confidence Interval (Narrower):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ci_95)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 3.595525 3.508873 3.682177</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"95% Prediction Interval (Wider):"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95% Prediction Interval (Wider):"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pi_95)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit        lwr      upr
1 3.595525 -0.7366093 7.927659</code></pre>
</div>
</div>
<p><strong>Written Analysis:</strong> The output clearly demonstrates the fundamental difference in uncertainty between predicting a population mean and predicting an individual data point. - The <strong>95% Confidence Interval</strong> is very narrow <code>[3.51, 3.68]</code>. This tells us that if we gathered <em>thousands</em> of observations that all have these exact median characteristics, their <em>average</em> <code>y</code> value is highly likely to fall in this tight 0.18-unit range. - The <strong>95% Prediction Interval</strong> is massively wider <code>[-0.74, 7.93]</code>. This estimates the exact <code>y</code> value for <strong>one single, newly generated observation</strong>. It is much wider because it must account for the irreducible error (<span class="math inline">\(\epsilon\)</span>). If a stakeholder asks “What is the expected <em>average</em> outcome for this data profile?”, we use the CI. If they ask “What will the outcome be for this <em>one specific</em> new occurrence?”, we must use the much wider PI to accurately communicate the higher level of uncertainty.</p>
</section>
</section>
<section id="typical-exam-discussion-questions-theory-interpretation" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="typical-exam-discussion-questions-theory-interpretation"><span class="header-section-number">1.8</span> 1.8 Typical Exam Discussion Questions (Theory &amp; Interpretation)</h2>
<p>In BAN404, writing code is only half the battle. The professor will almost certainly follow up your modeling steps with theoretical questions to test if you actually understand the math and tradeoffs behind the code. Here are 10 highly probable exam questions based on this specific dataset and the methods we just applied.</p>
<section id="q1-gam-vs.-manual-polynomial" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="q1-gam-vs.-manual-polynomial"><span class="header-section-number">1.8.1</span> Q1: GAM vs.&nbsp;Manual Polynomial</h3>
<p><strong>Question:</strong> <em>Both the GAM and the Polynomial OLS model attempted to fix the non-linearity in the data. Why did the GAM significantly outperform the manual polynomial approach (Test MSE 1.54 vs.&nbsp;3.05)?</em> <strong>Exam-Ready Answer:</strong> The manual polynomial <code>I(x2^2)</code> applied a <strong>global parametric fit</strong>. It forced a single, rigid parabola over the entire dataset for <code>x2</code> and completely ignored the non-linearity in <code>x3</code>. A GAM, however, uses <strong>smoothing splines</strong> (<code>s(x2)</code>, <code>s(x3)</code>). Splines provide <strong>local flexibility</strong>, meaning they bend dynamically across different regions of the data without forcing a strict mathematical shape. By capturing the exact local curves of both <code>x2</code> and <code>x3</code> without inflating variance, the GAM achieved a much lower bias than the rigid global polynomial.</p>
</section>
<section id="q2-lasso-vs.-ridge-regression" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="q2-lasso-vs.-ridge-regression"><span class="header-section-number">1.8.2</span> Q2: LASSO vs.&nbsp;Ridge Regression</h3>
<p><strong>Question:</strong> <em>We used LASSO regression in this analysis. Why was LASSO preferred over Ridge Regression given the findings in our EDA?</em> <strong>Exam-Ready Answer:</strong> Our EDA correlation matrix showed zero multicollinearity between the predictors, meaning Ridge’s primary benefit (stabilizing highly correlated coefficients) was unnecessary. However, the EDA also showed that <code>x4</code> and <code>x6</code> were pure noise (flat lines). LASSO uses an <strong>L1 penalty</strong> (absolute value), which has the mathematical property of shrinking useless coefficients to exactly zero. Ridge uses an L2 penalty, which shrinks them <em>towards</em> zero but never exactly to zero. Therefore, LASSO was preferred because it performs <strong>automatic variable selection</strong>, dropping the noise variables entirely and resulting in a simpler, more interpretable model.</p>
</section>
<section id="q3-bias-variance-tradeoff-in-ensembles" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="q3-bias-variance-tradeoff-in-ensembles"><span class="header-section-number">1.8.3</span> Q3: Bias-Variance Tradeoff in Ensembles</h3>
<p><strong>Question:</strong> <em>Explain how Random Forest and Gradient Boosting take fundamentally different approaches to the Bias-Variance tradeoff.</em></p>
<p><strong>Exam-Ready Answer:</strong> Random Forests use bagging (bootstrap aggregating). They build hundreds of deep, fully grown trees (low bias, high variance) independently, and then average their predictions to drastically reduce <strong>Variance</strong>. Boosting takes the exact opposite approach. It builds shallow, weak trees (high bias, low variance) sequentially. Each new tree learns from the <em>residuals</em> (mistakes) of the previous trees. Because it constantly attacks its own errors, Boosting is fundamentally an algorithm designed to reduce <strong>Bias</strong>.</p>
</section>
<section id="q4-the-danger-of-interpreting-ols-p-values-blindly" class="level3" data-number="1.8.4">
<h3 data-number="1.8.4" class="anchored" data-anchor-id="q4-the-danger-of-interpreting-ols-p-values-blindly"><span class="header-section-number">1.8.4</span> Q4: The Danger of Interpreting OLS p-values blindly</h3>
<p><strong>Question:</strong> <em>In the baseline OLS model, the variable <code>x2</code> likely had a coefficient near 0 and a non-significant p-value. Does this mean <code>x2</code> has no relationship with <code>y</code>?</em></p>
<p><strong>Exam-Ready Answer:</strong> No.&nbsp;OLS assumes a strict linear relationship. Because the true relationship between <code>x2</code> and <code>y</code> is a perfect U-shape (quadratic), a straight line drawn through it will have a slope of zero. The non-significant p-value only means there is no <em>linear</em> relationship. This highlights the danger of interpreting linear model outputs without performing EDA; a variable can have a massive non-linear effect while appearing completely useless to standard OLS.</p>
</section>
<section id="q5-bootstrapping-vs.-asymptotic-theory" class="level3" data-number="1.8.5">
<h3 data-number="1.8.5" class="anchored" data-anchor-id="q5-bootstrapping-vs.-asymptotic-theory"><span class="header-section-number">1.8.5</span> Q5: Bootstrapping vs.&nbsp;Asymptotic Theory</h3>
<p><strong>Question:</strong> <em>Why did we use the Percentile Bootstrap Confidence Interval for the <code>x1</code> coefficient instead of relying on the standard <code>summary(lm())</code> output or the Normal Approximation CI?</em></p>
<p><strong>Exam-Ready Answer:</strong> Standard OLS standard errors (and by extension, the Normal Approximation) rely on asymptotic theory, assuming that the model’s residuals are perfectly normally distributed. Our EDA showed that <code>y</code> is highly right-skewed, meaning the residuals are likely non-normal, which mathematically invalidates the OLS p-values. The Percentile Bootstrap makes <strong>zero distributional assumptions</strong>. It empirically estimates the uncertainty by resampling the actual data, meaning it naturally adapts to the skewness and provides a much more robust and honest Confidence Interval.</p>
</section>
<section id="q6-interpretability-vs.-flexibility" class="level3" data-number="1.8.6">
<h3 data-number="1.8.6" class="anchored" data-anchor-id="q6-interpretability-vs.-flexibility"><span class="header-section-number">1.8.6</span> Q6: Interpretability vs.&nbsp;Flexibility</h3>
<p><strong>Question:</strong> <em>Compare the Generalized Additive Model (GAM) to the Random Forest in terms of the interpretability-flexibility tradeoff.</em></p>
<p><strong>Exam-Ready Answer:</strong> Both models are highly flexible and capable of capturing severe non-linearities. However, a Random Forest is a “black box”—it handles complex interactions automatically, but we cannot write down a mathematical equation or easily visualize how all variables interact simultaneously. A GAM restricts the model to an <strong>additive structure</strong> (<span class="math inline">\(y = f(x_1) + f(x_2) ...\)</span>). While it cannot automatically capture complex interactions between variables like a tree can, this additivity allows us to isolate and plot the exact partial effect of each variable (the Partial Dependence Plots), making the GAM vastly more interpretable for business stakeholders.</p>
</section>
<section id="q7-the-role-of-mtry-in-random-forests" class="level3" data-number="1.8.7">
<h3 data-number="1.8.7" class="anchored" data-anchor-id="q7-the-role-of-mtry-in-random-forests"><span class="header-section-number">1.8.7</span> Q7: The Role of <code>mtry</code> in Random Forests</h3>
<p><strong>Question:</strong> <em>What is the purpose of the <code>mtry</code> parameter in a Random Forest, and how does it represent an improvement over standard Bagging?</em></p>
<p><strong>Exam-Ready Answer:</strong> In standard Bagging, every tree has access to all predictors. If there is one dominant predictor, almost all bagged trees will use it for their top split, making the trees highly correlated. Averaging correlated trees doesn’t reduce variance effectively. The <code>mtry</code> parameter in Random Forest forces the algorithm to only consider a random subset of predictors at each split. This intentionally <strong>decorrelates the trees</strong>, so that when their predictions are averaged, the Variance reduction is maximized.</p>
</section>
<section id="q8-evaluating-out-of-sample-performance" class="level3" data-number="1.8.8">
<h3 data-number="1.8.8" class="anchored" data-anchor-id="q8-evaluating-out-of-sample-performance"><span class="header-section-number">1.8.8</span> Q8: Evaluating Out-of-Sample Performance</h3>
<p><strong>Question:</strong> <em>Why do we rely on Test MSE to compare our 6 models rather than simply looking at which model has the lowest Training MSE?</em></p>
<p><strong>Exam-Ready Answer:</strong> Training MSE almost always decreases as model complexity increases. A highly flexible model (like a deep Random Forest) can perfectly memorize the training data, leading to a Training MSE near zero. However, this is <strong>overfitting</strong>—the model learns the noise rather than the signal, and will fail catastrophically on new data. Test MSE evaluates the model on a completely unseen holdout set, providing an honest, unbiased estimate of how well the model actually generalizes to the real world.</p>
</section>
<section id="q9-overfitting-in-boosting" class="level3" data-number="1.8.9">
<h3 data-number="1.8.9" class="anchored" data-anchor-id="q9-overfitting-in-boosting"><span class="header-section-number">1.8.9</span> Q9: Overfitting in Boosting</h3>
<p><strong>Question:</strong> <em>Can a Gradient Boosting model (GBM) overfit? How do the <code>n.trees</code> and <code>shrinkage</code> parameters interact to prevent this?</em></p>
<p><strong>Exam-Ready Answer:</strong> Yes. Unlike Random Forests (where adding more trees just stabilizes the variance), adding too many trees in Boosting will eventually cause the model to overfit, because it will start perfectly modeling the random noise in the residuals. To prevent this, we use the <code>shrinkage</code> (learning rate) parameter. A small shrinkage value (e.g., 0.01) forces the algorithm to learn very slowly. This requires a higher <code>n.trees</code> to achieve good performance, but makes the model much more robust against overfitting.</p>
</section>
<section id="q10-feature-importance-in-trees-vs.-linear-coefficients" class="level3" data-number="1.8.10">
<h3 data-number="1.8.10" class="anchored" data-anchor-id="q10-feature-importance-in-trees-vs.-linear-coefficients"><span class="header-section-number">1.8.10</span> Q10: Feature Importance in Trees vs.&nbsp;Linear Coefficients</h3>
<p><strong>Question:</strong> <em>How does the interpretation of “Variable Importance” in a Random Forest differ from the coefficients in our Polynomial OLS model?</em></p>
<p><strong>Exam-Ready Answer:</strong> In the Polynomial OLS model, the coefficients give us a precise marginal effect: “holding all else constant, a 1-unit increase in <span class="math inline">\(x\)</span> leads to a <span class="math inline">\(\beta\)</span> increase in <span class="math inline">\(y\)</span>.” It provides direction (positive/negative) and magnitude. Random Forest Variable Importance (like Increase in Node Purity) does not provide direction or a mathematical equation. It simply tells us how much worse the model’s overall error would be if we removed that variable. It is a measure of relative predictive contribution, not a marginal inference tool.</p>
</section>
<section id="q11-bias-reduction-vs.-variance-reduction-in-this-dataset" class="level3" data-number="1.8.11">
<h3 data-number="1.8.11" class="anchored" data-anchor-id="q11-bias-reduction-vs.-variance-reduction-in-this-dataset"><span class="header-section-number">1.8.11</span> Q11: Bias Reduction vs.&nbsp;Variance Reduction in this Dataset</h3>
<p><strong>Question:</strong> <em>Looking at the performance across all models for this specific dataset, was it bias reduction or variance reduction that had the largest impact on improving model fit? Why?</em></p>
<p><strong>Exam-Ready Answer:</strong> <strong>Bias reduction</strong> was overwhelmingly the most important factor for this dataset. The baseline OLS model suffered from severe underfitting (high bias) because its rigid straight-line assumption fundamentally missed the U-shaped signal in <code>x2</code> and the curve in <code>x3</code> (Test MSE ~5.08). While LASSO successfully performed <em>variance reduction</em> by dropping the noise variables (<code>x4</code>, <code>x6</code>), its MSE barely improved because the massive bias remained untouched. The moment we introduced models capable of bending to the data (Polynomials, Random Forest, GAM), the bias plummeted, and the Test MSE dropped massively (down to ~1.54). Thus, curing the functional form misspecification (bias) was the key to cracking this dataset.</p>
</section>
<section id="q12-justifying-specific-code-choices-the-gam-formula" class="level3" data-number="1.8.12">
<h3 data-number="1.8.12" class="anchored" data-anchor-id="q12-justifying-specific-code-choices-the-gam-formula"><span class="header-section-number">1.8.12</span> Q12: Justifying Specific Code Choices (The GAM Formula)</h3>
<p><strong>Question:</strong> <em>In the GAM implementation, you used the formula <code>y ~ x1 + s(x2) + s(x3) + x5</code>. Why did you specifically choose this formula instead of wrapping every variable in a smoothing spline <code>s()</code> or including all variables?</em></p>
<p><strong>Exam-Ready Answer:</strong> This specific formula was a conscious choice based entirely on the visual EDA and LASSO results, perfectly balancing bias and variance: 1. <strong>Excluded <code>x4</code> and <code>x6</code>:</strong> Both EDA and LASSO proved these were pure noise. Excluding them prevents the model from fitting to random fluctuations (<em>reducing Variance</em>). 2. <strong>Linear <code>x1</code> and <code>x5</code>:</strong> The EDA showed these have perfectly straight relationships with <code>y</code>. Wrapping them in <code>s()</code> would waste degrees of freedom and risk overfitting. Leaving them as linear terms keeps the model simple and robust (<em>preventing Variance</em>). 3. <strong>Smoothed <code>s(x2)</code> and <code>s(x3)</code>:</strong> The EDA showed these variables have severe curves. Wrapping only these in splines allows the model to capture the complex shapes (<em>reducing Bias</em>). By manually curating the formula, we avoided the “black-box” approach and built an incredibly efficient model tailored exactly to the true data-generating process.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>